name: CI

on: [pull_request]

jobs:
  selenium:
    name: Selenium Smoke Test
    runs-on: ubuntu-latest
    container: openstax/rex-web:CI
    steps:
    - uses: actions/checkout@v2
    - name: find deployment
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        review_url=$(./concourse/common/get_review_environment)
        echo "::set-env name=BASE_URL::$review_url"
    - name: selenium
      env:
        BROWSER: 'Chrome'
        MARKER: 'smoke_test'
        SAUCELABS_USERNAME: ${{ secrets.saucelabs_username }}
        SAUCELABS_API_KEY: ${{ secrets.saucelabs_api_key }}
        SECURE_STORE_PASSWORD: ${{ secrets.secure_store_password }}
      run: make sauce
